../bin/run: main.cpp init/glbcova.cpp init/init.cpp estimate/estimateGo.cpp run/runGo.cpp datadeal/dealfor.cpp box/boxoperation.cpp fun/force.cpp list/listroutine.cpp inout/readin.cpp tools/auxiliarytool.cpp tools/progress-bar.cpp tools/gbsa_f2c.cpp fun/energy.cpp inout/writeout.cpp diagnostics/diagnostics.cpp fun/potential.cpp tools/move.cpp
	g++ main.cpp init/glbcova.cpp init/init.cpp estimate/estimateGo.cpp run/runGo.cpp datadeal/dealfor.cpp box/boxoperation.cpp fun/force.cpp list/listroutine.cpp inout/readin.cpp tools/auxiliarytool.cpp tools/progress-bar.cpp tools/gbsa_f2c.cpp fun/energy.cpp inout/writeout.cpp diagnostics/diagnostics.cpp fun/potential.cpp tools/move.cpp -o ../bin/run.out

clean:
	-rm ../bin/run.out
