../bin/run: main.c init/glbcova.c init/init.c estimate/estimateGo.c run/runGo.c datadeal/dealfor.c box/boxoperation.c fun/force.c list/listroutine.c inout/readin.c tools/auxiliarytool.c
	g++ main.c init/glbcova.c init/init.c estimate/estimateGo.c run/runGo.c datadeal/dealfor.c box/boxoperation.c fun/force.c list/listroutine.c inout/readin.c tools/auxiliarytool.c -o ../bin/run.out

clean:
	-rm ../bin/run.out
