../bin/run: main.c init/glbcova.c init/init.c estimate/estimateGo.c run/runGo.c datadeal/dealfor.c box/boxoperation.c fun/force.c list/listroutine.c inout/readin.c tools/auxiliarytool.c tools/progress-bar.c tools/gbsa_f2c.c
	g++ main.c init/glbcova.c init/init.c estimate/estimateGo.c run/runGo.c datadeal/dealfor.c box/boxoperation.c fun/force.c list/listroutine.c inout/readin.c tools/auxiliarytool.c tools/progress-bar.c tools/gbsa_f2c.c -o ../bin/run.out -lncurses

clean:
	-rm ../bin/run.out
